### ISSUE TITLE
Implement grade placeholder

### ISSUE THREAD

**Issue by robertlandreaux** [robertlandreaux/Gradejoy#17]
When a student does not need a grade for an assignment because of an absence, exemption, etc..., the user/teacher should be able to place an "X" in the grade's points_earned field. The "X" will ensure that the assignment is not factored into a student's average.

**Comment by jaimerump** [comment]
That's very long for an issue title. I would recommend setting the title to something like "Implement grade placeholder" and setting that as the description.

**Comment by robertlandreaux** [comment]
Thanks, Jaime! I will.
